# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'RCTText',
  'RCTImage',
  'RCTNetwork',
  'RCTWebSocket',
]

target 'BigChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for BigChat
 pod 'FBSDKLoginKit'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
  target 'BigChat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

    pod 'RNShare', :path => '../node_modules/react-native-share'

    pod 'RNSound', :path => '../node_modules/react-native-sound'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'react-native-video', :path => '../node_modules/react-native-video'

    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

    pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  end

  target 'BigChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BigChat-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BigChat-tvOS

  target 'BigChat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
